version: 2.1
commands:
    print_pipeline_id:
        steps:
            - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
    build:
        docker:
          - image: circleci/node:13.8.0
        steps:
            - checkout
            - run:
                  name: build project
                  command: npm run lint
    test:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - run: npm run test
    analyze:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - run: npm audit

workflows:
    my_workflow:
        jobs:
            - build
            - test:
                requires:
                    - build
            - analyze:
                requires:
                    - test